name: Release from Google Drive

on:
  workflow_dispatch:
    inputs:
      google_drive_url:
        description: 'URL de Google Drive'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install requests

    - name: Download file from Google Drive
      run: |
        python download_and_release.py "${{ github.event.inputs.google_drive_url }}"

    - name: Create release and upload asset
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: "./downloaded_file"
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
