name: Descargar y Subir archivo como Release

on:
  workflow_dispatch:
    inputs:
      google_drive_link:
        description: "Enlace de Google Drive para descargar el archivo"
        required: true
        type: string

jobs:
  descargar_y_subir:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar código fuente
      uses: actions/checkout@v2

    - name: Establecer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Descargar archivo desde Google Drive
      run: |
        python main.py ${{ github.event.inputs.google_drive_link }}

    - name: Subir archivo a GitHub Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: |
          *
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
